import { Event } from '@mosqueconnect/shared-types';

export const events: Event[] = [
  { 
    id: 'e1', 
    mosqueId: '1', 
    title: 'Community Iftar', 
    description: 'Join us for a community-wide Iftar during the middle of Ramadan. All are welcome.',
    startDate: '2026-03-25', 
    endDate: '2026-03-25',
    startTime: '18:15',
    endTime: '20:00',
    category: 'iftar',
    location: 'Main Community Hall',
    locationType: 'onsite',
    isFree: true,
    price: 0,
    attendeeCount: 150,
    imageUrl: 'https://images.unsplash.com/photo-1590076215667-873d6f00918c?auto=format&fit=crop&q=80&w=800',
    isRecurring: false,
    isActive: true,
    createdAt: new Date().toISOString()
  },
  { 
    id: 'e2', 
    mosqueId: '1', 
    title: 'Quran Study Circle', 
    description: 'Weekly in-depth study of the Quranic text with our Head Imam.',
    startDate: '2026-03-27', 
    endDate: '2026-03-27',
    startTime: '19:00',
    endTime: '20:30',
    category: 'quran_study',
    location: 'Mosque Library',
    locationType: 'onsite',
    isFree: true,
    price: 0,
    attendeeCount: 45,
    imageUrl: 'https://images.unsplash.com/photo-1544890225-2f3faec4cd60?auto=format&fit=crop&q=80&w=400',
    isRecurring: true,
    recurrencePattern: 'weekly',
    isActive: true,
    createdAt: new Date().toISOString()
  },
  { 
    id: 'e3', 
    mosqueId: '2', 
    title: 'Youth Sports Day', 
    description: 'A day of fun and sports activities for the youth of our community.',
    startDate: '2026-04-05', 
    endDate: '2026-04-05',
    startTime: '10:00',
    endTime: '15:00',
    category: 'community_event',
    location: 'Local Park',
    locationType: 'offsite',
    isFree: false,
    price: 5,
    attendeeCount: 80,
    imageUrl: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&q=80&w=800',
    isRecurring: false,
    isActive: true,
    createdAt: new Date().toISOString()
  }
];
